#!/bin/sh
#
# Slate server installer (macOS) - BETA.
#
# UNVERIFIED ON REAL HARDWARE. There is no Mac in the development fleet, so
# this script has been shellchecked and dry-run on Linux but has never been
# executed on a Mac. It ships marked beta, says so at every run, and the guide
# steers a Mac owner towards a Linux box or the Slate appliance first. The
# first real run is a human gate (docs/owner-todo.md); please report what it
# did.
#
# What it does, and why it is shaped this way. macOS has no WSL, and Docker
# Desktop on a Mac runs its Linux VM behind NAT, so a container there hears
# its own VM and nothing on the LAN - every mDNS integration (Cast, Hue,
# Lutron, Ecobee HAP) fails silently and the Matter lock cannot be
# commissioned. What does work is what works for any hypervisor: a Linux VM
# with a BRIDGED network interface, so the VM is a real machine on the LAN
# with its own address, mDNS and IPv6 link-local. On macOS that is Lima
# (Apple's Virtualization framework, no kernel extension) with socket_vmnet
# for bridging. Inside that VM the Linux installer runs unchanged.
#
# The one-time root steps, and why they exist:
#   * socket_vmnet must be installed somewhere only root can alter.
#     Lima's documentation says outright that a Homebrew-installed
#     socket_vmnet "is not secure and not recommended by the Lima project" -
#     the binary must be root-owned, and Lima >= 1.0 refuses anything else -
#     so this installs the release binary under /opt/socket_vmnet, as Lima's
#     own instructions do. (docs/onboarding.md said `brew install
#     socket_vmnet`; that is the path Lima refuses.)
#   * /etc/sudoers.d/lima, generated by `limactl sudoers`, lets Lima start
#     socket_vmnet as root without a password prompt every boot.
#
# The honest caveats, printed at the end too: the Mac must be ALWAYS ON and
# WIRED - a Mac mini in a cupboard qualifies, a MacBook that sleeps does not,
# because this server holds the Matter fabric and the recordings. Bridging
# over Wi-Fi is unreliable with vmnet and is warned about, not refused.
#
# Apple Silicon and Intel: Lima's `vz` type needs macOS 13 or later on
# either, and socket_vmnet publishes both arm64 and x86_64 builds. Nothing in
# the documentation says bridged networking is unavailable on Intel, so
# neither is refused - but Intel is the less-travelled path and is called out
# as such in the output.
#
# POSIX sh on purpose - macOS ships /bin/sh as bash-in-POSIX-mode, but the
# same script must also dry-run on Linux in CI.
#
# Usage: sh slate-install-mac.sh [--dry-run] [--interface enX] [--help]
#        curl -fsSL https://get.slatepanel.app/mac | sh

set -eu

# ---------------------------------------------------------------- constants

SLATE_DIST_RAW_DEFAULT="https://raw.githubusercontent.com/dfalpha/slate-dist/main"
SLATE_DIST_RAW="${SLATE_DIST_RAW:-$SLATE_DIST_RAW_DEFAULT}"

VM_NAME="${SLATE_VM_NAME:-slate}"
VM_CPUS="${SLATE_VM_CPUS:-4}"
VM_MEMORY_GB="${SLATE_VM_MEMORY_GB:-8}"
VM_DISK_GB="${SLATE_VM_DISK_GB:-128}"
VM_TEMPLATE="template://ubuntu-24.04"

# Pinned, like every other dependency this project takes. The release
# publishes socket_vmnet-<ver>-arm64.tar.gz and socket_vmnet-<ver>-x86_64.tar.gz,
# which is exactly what `uname -m` says on each kind of Mac.
SOCKET_VMNET_VERSION="${SLATE_SOCKET_VMNET_VERSION:-1.2.2}"
SOCKET_VMNET_PREFIX="/opt/socket_vmnet"
SOCKET_VMNET_BIN="$SOCKET_VMNET_PREFIX/bin/socket_vmnet"

LIMA_NETWORKS_FILE="$HOME/.lima/_config/networks.yaml"
LIMA_SUDOERS_FILE="/etc/sudoers.d/lima"

SLATE_PORTAL_LINK_URL="https://portal.slatepanel.app/account/link"

DRY_RUN=0
PREFLIGHT_PROBLEMS=0
BRIDGE_IF="${SLATE_BRIDGE_INTERFACE:-}"

# ------------------------------------------------------------------- output

log()  { printf '%s\n' "$*"; }
info() { printf '  %s\n' "$*"; }
warn() { printf 'WARNING: %s\n' "$*" >&2; }
step() { printf '\n== %s\n' "$*"; }

die() {
    printf '\nERROR: %s\n' "$*" >&2
    exit 1
}

# A preflight failure: fatal for real, reported and skipped under --dry-run
# so the whole flow can be walked on a machine that is not a Mac (CI).
fatal_or_note() {
    if [ "$DRY_RUN" -eq 1 ]; then
        printf 'WOULD ABORT: %s\n' "$*" >&2
        PREFLIGHT_PROBLEMS=$((PREFLIGHT_PROBLEMS + 1))
    else
        die "$*"
    fi
}

have() { command -v "$1" >/dev/null 2>&1; }

run() {
    if [ "$DRY_RUN" -eq 1 ]; then
        printf '  [dry-run] %s\n' "$*"
        return 0
    fi
    "$@"
}

usage() {
    cat <<'USAGE'
slate-install-mac.sh - install and start a Slate server on macOS (BETA)

Usage:
  sh slate-install-mac.sh [options]        (as your own user, NOT with sudo;
                                            it asks for sudo where needed)

Options:
  --dry-run            Print every action without changing anything. Preflight
                       failures are reported as "WOULD ABORT" instead of
                       stopping, so the whole flow can be exercised anywhere.
  --interface NAME     The Mac's LAN interface to bridge (e.g. en0). Default:
                       the interface carrying the default route.
  -h, --help           This text.

Environment (all optional):
  SLATE_BRIDGE_INTERFACE   Same as --interface.
  SLATE_VM_CPUS / SLATE_VM_MEMORY_GB / SLATE_VM_DISK_GB   VM size (4 / 8 / 128).
  SLATE_DIST_RAW           Base URL of the public dist mirror (for testing).

What it does:
  1. Refuses to run where this cannot work: not macOS, run as root, macOS
     older than 13, or no Homebrew (and says how to install it).
  2. brew install lima.
  3. Installs socket_vmnet's release binary under /opt/socket_vmnet, root
     owned (one sudo), and Lima's sudoers file (one more sudo).
  4. Writes ~/.lima/_config/networks.yaml with a `bridged` network on your
     LAN interface.
  5. Starts an Ubuntu 24.04 VM named "slate" (vz, bridged, 4 CPU / 8 GB /
     128 GB by default).
  6. Runs the Linux installer inside it - which installs Docker, pulls the
     public images, writes .env without asking anything, starts the stack and
     VERIFIES host networking from inside the VM.
  7. Opens Slate's single-use first-setup page in your browser, where you
     create the administrator and link the server to your Slate account.

Re-running is safe: Lima, socket_vmnet, the network config and the VM are all
detected and reused.

BETA: unverified on real hardware. See the header of this script.
USAGE
}

# --------------------------------------------------------------- arg parsing

while [ $# -gt 0 ]; do
    case "$1" in
        --dry-run) DRY_RUN=1 ;;
        --interface)
            [ $# -ge 2 ] || die "--interface needs a name (e.g. en0)"
            BRIDGE_IF="$2"
            shift
            ;;
        --interface=*) BRIDGE_IF="${1#--interface=}" ;;
        -h|--help) usage; exit 0 ;;
        *) printf 'Unknown option: %s\n\n' "$1" >&2; usage >&2; exit 2 ;;
    esac
    shift
done

# ---------------------------------------------------------------- preflight

macos_major() {
    sw_vers -productVersion 2>/dev/null | cut -d. -f1
}

preflight() {
    step "Preflight"

    os=$(uname -s 2>/dev/null || echo unknown)
    if [ "$os" != "Darwin" ]; then
        fatal_or_note "This is the macOS installer and this is $os. On Linux: curl -fsSL https://get.slatepanel.app/linux | sudo sh. On Windows 11, in an elevated PowerShell 7: irm https://get.slatepanel.app/windows | iex"
    else
        info "OS: macOS $(sw_vers -productVersion 2>/dev/null || echo '?') ($(uname -m))"
    fi

    if [ "$(id -u)" = "0" ]; then
        fatal_or_note "Run this as your own user, not with sudo. Homebrew refuses to run as root, and Lima's VM belongs to the user who starts it. The script asks for sudo for the two steps that need it."
    else
        info "Running as $(id -un 2>/dev/null || echo 'a normal user')."
    fi

    if [ "$os" = "Darwin" ]; then
        major=$(macos_major)
        case "$major" in
            ''|*[!0-9]*) warn "Could not read the macOS version; Lima's vz driver needs macOS 13 or later." ;;
            *)
                if [ "$major" -lt 13 ]; then
                    fatal_or_note "macOS $major is too old: Lima's vz driver (Apple's Virtualization framework) needs macOS 13 or later."
                fi
                ;;
        esac
        case "$(uname -m)" in
            arm64) info "Apple Silicon." ;;
            x86_64) info "Intel Mac. Lima vz and socket_vmnet both support Intel, but this path is UNVERIFIED ON INTEL - less travelled than Apple Silicon." ;;
            *) warn "Unknown architecture $(uname -m); socket_vmnet publishes arm64 and x86_64 builds only." ;;
        esac
        case "$(sysctl -n hw.model 2>/dev/null || true)" in
            MacBook*) warn "This is a MacBook. A Slate server must be ALWAYS ON and WIRED: it holds the Matter fabric and the security recordings, and a laptop that sleeps or roams takes the whole house's dashboards with it. A Mac mini in a cupboard is the right home." ;;
        esac
    fi

    if have brew; then
        info "Homebrew: $(brew --version 2>/dev/null | head -n 1)"
    else
        fatal_or_note "Homebrew is required (it installs Lima). Install it first: /bin/bash -c \"\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\" - then re-run this script."
    fi

    if [ -d /Applications/Docker.app ]; then
        info "Docker Desktop is installed. It is not used and does not need removing: its VM is behind NAT and cannot reach the LAN, which is why a bridged Lima VM is used instead."
    fi

    if ! have curl; then
        fatal_or_note "curl is missing. It ships with macOS, so this is unexpected."
    fi

    pick_bridge_interface
}

# The interface carrying the default route, unless told otherwise. Wired is
# what Slate wants; vmnet bridging over Wi-Fi is known to be flaky, and the
# server should not be on Wi-Fi in any case.
pick_bridge_interface() {
    if [ -z "$BRIDGE_IF" ] && [ "$(uname -s)" = "Darwin" ]; then
        BRIDGE_IF=$(route -n get default 2>/dev/null | awk '/interface:/ {print $2; exit}')
    fi
    if [ -z "$BRIDGE_IF" ]; then
        if [ "$DRY_RUN" -eq 1 ]; then
            BRIDGE_IF="en0"
            info "[dry-run] no default route interface found here; assuming en0."
        else
            die "Could not find the interface carrying the default route. Pass --interface (e.g. en0; see 'networksetup -listallhardwareports')."
        fi
    fi
    info "LAN interface to bridge: $BRIDGE_IF"

    if [ "$(uname -s)" = "Darwin" ] && have networksetup; then
        port=$(networksetup -listallhardwareports 2>/dev/null |
            awk -v want="$BRIDGE_IF" '/^Hardware Port:/ {p=$0; sub(/^Hardware Port: /, "", p)} /^Device:/ && $2 == want {print p; exit}')
        case "$port" in
            *Wi-Fi*|*AirPort*)
                warn "$BRIDGE_IF is Wi-Fi ($port). Bridging a VM over Wi-Fi is unreliable, and an always-on server should be on a cable. Plug in Ethernet and re-run with --interface <that port> if this does not work."
                ;;
            '') ;;
            *) info "$BRIDGE_IF is '$port'." ;;
        esac
    fi
}

# --------------------------------------------------------------------- lima

ensure_lima() {
    step "Lima"
    if have limactl; then
        info "Already installed: $(limactl --version 2>/dev/null || echo limactl)"
    else
        run brew install lima
    fi
}

# Lima's own instructions: the binary in a root-only location, never
# Homebrew's user-writable prefix. Verified against the release asset names:
# socket_vmnet-<ver>-{arm64,x86_64}.tar.gz, extracting to opt/socket_vmnet/.
ensure_socket_vmnet() {
    step "socket_vmnet (bridged networking helper, root-owned)"

    if [ -x "$SOCKET_VMNET_BIN" ]; then
        owner=$(stat -f '%Su' "$SOCKET_VMNET_BIN" 2>/dev/null || stat -c '%U' "$SOCKET_VMNET_BIN" 2>/dev/null || echo '?')
        if [ "$owner" = "root" ]; then
            info "Already installed at $SOCKET_VMNET_BIN (owned by root)."
            return 0
        fi
        warn "$SOCKET_VMNET_BIN exists but is owned by '$owner', not root. Lima refuses that; reinstalling."
    fi

    arch=$(uname -m)
    tarball="socket_vmnet-${SOCKET_VMNET_VERSION}-${arch}.tar.gz"
    url="https://github.com/lima-vm/socket_vmnet/releases/download/v${SOCKET_VMNET_VERSION}/${tarball}"
    tmpdir=$(mktemp -d)
    info "Downloading $url"
    run curl -fsSL -o "$tmpdir/$tarball" "$url"
    info "Extracting into / (creates $SOCKET_VMNET_PREFIX, owned by root). This asks for your password."
    run sudo tar Cxzf / "$tmpdir/$tarball" opt/socket_vmnet
    rm -rf "$tmpdir"
    if [ "$DRY_RUN" -eq 0 ]; then
        [ -x "$SOCKET_VMNET_BIN" ] || die "$SOCKET_VMNET_BIN is missing after the install. The release tarball's layout may have changed; see https://github.com/lima-vm/socket_vmnet/releases"
    fi
}

# ~/.lima/_config/networks.yaml: where socket_vmnet lives and what "bridged"
# means. Written whole if absent; if present without our bridged interface,
# backed up and replaced (Lima reads this file only, so a partial edit of
# unknown YAML is riskier than a clean rewrite).
ensure_networks_yaml() {
    step "Lima network config ($LIMA_NETWORKS_FILE)"

    if [ -f "$LIMA_NETWORKS_FILE" ] &&
       grep -q "socketVMNet: *$SOCKET_VMNET_BIN" "$LIMA_NETWORKS_FILE" &&
       awk '/^  bridged:/ {b=1; next} b && /^  [^ ]/ {b=0} b && /interface:/ {print $2}' "$LIMA_NETWORKS_FILE" | grep -qx "$BRIDGE_IF"; then
        info "Already configured: bridged on $BRIDGE_IF via $SOCKET_VMNET_BIN."
        return 0
    fi

    if [ "$DRY_RUN" -eq 1 ]; then
        info "[dry-run] would write $LIMA_NETWORKS_FILE (bridged on $BRIDGE_IF), backing up any existing file."
        return 0
    fi

    mkdir -p "$(dirname "$LIMA_NETWORKS_FILE")"
    if [ -f "$LIMA_NETWORKS_FILE" ]; then
        backup="$LIMA_NETWORKS_FILE.bak-$(date +%Y%m%d-%H%M%S)"
        cp "$LIMA_NETWORKS_FILE" "$backup"
        warn "Existing $LIMA_NETWORKS_FILE backed up to $backup and replaced."
    fi
    cat > "$LIMA_NETWORKS_FILE" <<EOF
# Written by slate-install-mac.sh. Lima's networks.yaml.
#
# socket_vmnet lives under /opt (root-owned) rather than Homebrew's prefix
# because Lima requires the helper it runs as root to be alterable only by
# root. "bridged" puts the Slate VM on the Mac's own LAN, with its own
# address, mDNS and IPv6 link-local - the whole reason a VM is used at all.
paths:
  socketVMNet: $SOCKET_VMNET_BIN
  varRun: /private/var/run/lima
  sudoers: /private$LIMA_SUDOERS_FILE

group: everyone

networks:
  shared:
    mode: shared
    gateway: 192.168.105.1
    dhcpEnd: 192.168.105.254
    netmask: 255.255.255.0
  bridged:
    mode: bridged
    interface: $BRIDGE_IF
EOF
    info "Wrote $LIMA_NETWORKS_FILE (bridged on $BRIDGE_IF)."
}

# `limactl sudoers` prints the exact rules Lima needs for the paths in
# networks.yaml, and nothing else. Installed root-owned, 0440, like any
# sudoers drop-in. Re-run only if the content would change.
ensure_sudoers() {
    step "Lima sudoers ($LIMA_SUDOERS_FILE)"

    if [ "$DRY_RUN" -eq 1 ]; then
        info "[dry-run] limactl sudoers > <tmp>; sudo install -o root -g wheel -m 0440 <tmp> $LIMA_SUDOERS_FILE"
        return 0
    fi
    have limactl || die "limactl is not on PATH after the Lima install. Open a new terminal and re-run."

    tmp=$(mktemp)
    limactl sudoers > "$tmp" || die "'limactl sudoers' failed. Check $LIMA_NETWORKS_FILE."
    if [ -f "$LIMA_SUDOERS_FILE" ] && sudo cmp -s "$tmp" "$LIMA_SUDOERS_FILE"; then
        info "Already installed and current."
    else
        info "Installing (asks for your password)."
        sudo install -o root -g wheel -m 0440 "$tmp" "$LIMA_SUDOERS_FILE"
        info "Installed."
    fi
    rm -f "$tmp"
}

vm_exists() {
    limactl list --format '{{.Name}}' 2>/dev/null | grep -qx "$VM_NAME"
}

vm_status() {
    limactl list --format '{{.Name}} {{.Status}}' 2>/dev/null | awk -v n="$VM_NAME" '$1 == n {print $2; exit}'
}

ensure_vm() {
    step "The VM ($VM_NAME: Ubuntu 24.04, vz, bridged, ${VM_CPUS} CPU / ${VM_MEMORY_GB} GB / ${VM_DISK_GB} GB)"

    if [ "$DRY_RUN" -eq 1 ]; then
        info "[dry-run] limactl start --name=$VM_NAME --vm-type=vz --cpus=$VM_CPUS --memory=$VM_MEMORY_GB --disk=$VM_DISK_GB --network=lima:bridged --containerd=none --tty=false $VM_TEMPLATE"
        info "[dry-run] (or 'limactl start $VM_NAME' if it already exists and is stopped)"
        return 0
    fi

    if vm_exists; then
        status=$(vm_status)
        if [ "$status" = "Running" ]; then
            info "Already running."
        else
            info "Exists ($status); starting it."
            limactl start --tty=false "$VM_NAME" || die "'limactl start $VM_NAME' failed. 'limactl list' and ~/.lima/$VM_NAME/ha.stderr.log say why."
        fi
        return 0
    fi

    info "Creating it (downloads an Ubuntu cloud image, a few hundred MB)."
    limactl start \
        --name="$VM_NAME" \
        --vm-type=vz \
        --cpus="$VM_CPUS" \
        --memory="$VM_MEMORY_GB" \
        --disk="$VM_DISK_GB" \
        --network=lima:bridged \
        --containerd=none \
        --tty=false \
        "$VM_TEMPLATE" ||
        die "'limactl start' failed. If the error mentions socket_vmnet or sudo, check $LIMA_SUDOERS_FILE and $LIMA_NETWORKS_FILE; ~/.lima/$VM_NAME/ha.stderr.log has the detail."
}

# Lima does not start a VM at boot on its own. `limactl start-at-login`
# registers a LaunchAgent for it - a LaunchAgent, so it runs when this user
# logs in, which is the always-on posture the final screen asks for. Best
# effort: an old Lima without the command is a warning, not a failure.
ensure_start_at_login() {
    step "Start the VM at login"
    if [ "$DRY_RUN" -eq 1 ]; then
        info "[dry-run] limactl start-at-login $VM_NAME"
        return 0
    fi
    if limactl start-at-login "$VM_NAME" >/dev/null 2>&1; then
        info "Registered: the '$VM_NAME' VM starts when this user logs in."
    else
        warn "'limactl start-at-login $VM_NAME' failed (old Lima?). After a reboot, run 'limactl start $VM_NAME' by hand, or upgrade Lima with 'brew upgrade lima' and run that command."
    fi
}

# The VM's LAN address, on the bridged interface. Lima's user-mode network is
# 192.168.5.0/24 and its shared vmnet is 192.168.105.0/24; a real LAN address
# is anything else. Proof that bridging worked, before the Linux installer
# proves host networking inside the VM.
VM_LAN_IP=""
verify_vm_on_lan() {
    step "Verifying the VM is on the LAN"
    if [ "$DRY_RUN" -eq 1 ]; then
        info "[dry-run] would read the VM's IPv4 addresses and expect one outside 192.168.5.0/24 and 192.168.105.0/24."
        return 0
    fi
    addrs=$(limactl shell "$VM_NAME" -- sh -c "ip -4 -o addr show scope global 2>/dev/null | awk '{print \$4}'" 2>/dev/null || true)
    for a in $addrs; do
        case "$a" in
            192.168.5.*|192.168.105.*|127.*) ;;
            *) VM_LAN_IP="${a%/*}"; break ;;
        esac
    done
    if [ -n "$VM_LAN_IP" ]; then
        info "VM LAN address: $VM_LAN_IP (bridged on $BRIDGE_IF)"
    else
        warn "The VM has no address outside Lima's own networks (saw: ${addrs:-none}). Bridging did not give it a LAN address - check that $BRIDGE_IF is the right interface (--interface), that it is wired, and ~/.lima/$VM_NAME/ha.stderr.log. The Linux installer inside will report the same thing from its side."
    fi
}

# The Linux installer, unchanged, inside the VM. Downloaded to a file first
# rather than `curl | sh`, so any prompt (only the transitional GitHub-token
# fallback is left) has a clean stdin.
#
# SLATE_FIRST_SETUP=none: the VM is headless, and the link it would print
# carries the VM's view of things. This script asks for the link itself at the
# end and opens it in the Mac's own browser (show_first_setup).
run_linux_installer() {
    step "Running the Linux installer inside the VM"
    inner="curl -fsSL -o /tmp/slate-install.sh $SLATE_DIST_RAW/slate-install.sh && sh /tmp/slate-install.sh"
    if [ "$DRY_RUN" -eq 1 ]; then
        info "[dry-run] limactl shell $VM_NAME -- sudo env SLATE_FIRST_SETUP=none sh -c \"$inner\""
        return 0
    fi
    limactl shell "$VM_NAME" -- sudo env SLATE_FIRST_SETUP=none sh -c "$inner" ||
        die "The Linux installer failed inside the VM. Its own message above says why; re-run this script once it is fixed - everything up to here is reused."
}

# Prints (or with --new, rotates) the server's single-use first-setup link,
# run inside the VM. The server mints the token on its first start with no
# administrator; this only reads it out.
SETUP_URL_COMMAND="docker exec slate-server node dist/cli/firstSetupUrl.js"

# D12, 2026-09-15: "Browser opens; the setup wizard creates the admin.
# Installers ask nothing." Reads the link out of the server in the VM and opens
# it in this Mac's browser. The VM is bridged, so the Mac reaches it on its own
# LAN address; with no address found, localhost is the fallback (Lima forwards
# the guest's listening ports to it).
show_first_setup() {
    if [ "$DRY_RUN" -eq 1 ]; then
        info "[dry-run] would ask the server in the VM for its single-use first-setup link"
        info "[dry-run] (limactl shell $VM_NAME -- sudo $SETUP_URL_COMMAND) and open it with 'open'."
        return 0
    fi
    setup_host="${VM_LAN_IP:-localhost}"
    # Word splitting of SETUP_URL_COMMAND is intended: it is a command line.
    # shellcheck disable=SC2086
    if setup_url=$(limactl shell "$VM_NAME" -- sudo $SETUP_URL_COMMAND --host "$setup_host" 2>/dev/null); then
        setup_url=$(printf '%s\n' "$setup_url" | head -n 1)
    else
        setup_rc=$?
        setup_url=""
        if [ "$setup_rc" -eq 3 ]; then
            log "This server already has an administrator: sign in with that account."
            return 0
        fi
    fi
    case "$setup_url" in
        http://*"/admin/setup?t="*)
            log "Finish setting up in your browser: create the administrator, then link"
            log "this server to your Slate account. Opening:"
            log "  $setup_url"
            log "The link works once and expires after 24 hours. For a fresh one:"
            log "  limactl shell $VM_NAME -- sudo $SETUP_URL_COMMAND --new"
            if have open; then
                open "$setup_url" >/dev/null 2>&1 || warn "Could not open a browser; open the link above by hand."
            fi
            ;;
        *)
            log "Finish setting up in a browser. Print the single-use setup link with:"
            log "  limactl shell $VM_NAME -- sudo $SETUP_URL_COMMAND"
            ;;
    esac
    setup_url=""
}

finish() {
    printf '\n'
    if [ "$DRY_RUN" -eq 1 ]; then
        log "A real run would end here, with Slate installed in the '$VM_NAME' VM."
    else
        log "Slate is installed, in the '$VM_NAME' VM on this Mac."
    fi
    printf '\n'
    log "Admin panel:"
    if [ -n "$VM_LAN_IP" ]; then
        log "  http://$VM_LAN_IP:8080/admin"
    else
        log "  http://<the VM's LAN address>:8080/admin   (the Linux installer printed it)"
    fi
    printf '\n'
    show_first_setup
    printf '\n'
    log "Connect this server to your Slate account in the setup page's second"
    log "step. To do it later instead, sign in to the admin panel and"
    log "  open the Licence tab, click Link to my Slate account, and type the"
    log "  code at $SLATE_PORTAL_LINK_URL"
    printf '\n'
    log "Keep this Mac awake and on a cable. The VM is registered to start at"
    log "login (limactl start-at-login), so keep this user logged in after a"
    log "reboot. To stop sleep on a Mac mini:  sudo pmset -a sleep 0 disksleep 0"
    printf '\n'
    log "BETA: this macOS path is unverified on real hardware. If it worked,"
    log "or did not, please say so in a support ticket at the portal."

    if [ "$DRY_RUN" -eq 1 ]; then
        printf '\n'
        log "This was a dry run - nothing was changed."
        if [ "$PREFLIGHT_PROBLEMS" -gt 0 ]; then
            log "$PREFLIGHT_PROBLEMS preflight check(s) would have aborted a real run."
        fi
    fi
}

# ---------------------------------------------------------------------- main

log "Slate server installer for macOS - BETA (unverified on real hardware)"
if [ "$DRY_RUN" -eq 1 ]; then
    log "(dry run - nothing will be changed)"
fi

preflight
ensure_lima
ensure_socket_vmnet
ensure_networks_yaml
ensure_sudoers
ensure_vm
ensure_start_at_login
verify_vm_on_lan
run_linux_installer
finish
